version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld

workflows:
  sample: 
    jobs:
      - build-and-test